FROM node:10

RUN git clone https://github.com/Jmo-101/Eks_ecommerce_app.git

WORKDIR /Eks_ecommerce_app/frontend

EXPOSE 3000

RUN npm install --save-dev @babel/plugin-proposal-private-property-in-object
RUN npm install

CMD npm start
